### Tạo arr 

In [ ]:
import numpy as np 

arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr
arr.shape  # kích thước 
type(arr) # kiểu dữ liệu 

numpy.ndarray

### Tạo arr_odd và arr_even

In [8]:
arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]
arr_odd

array([1, 3, 5, 7, 9])

In [9]:
arr_even

array([0, 2, 4, 6, 8])

### Tạo arr_update_1

In [17]:
arr[arr_odd] = 100


In [18]:
arr_update_1 = arr
arr_update_1

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])