In [5]:
import numpy as np 


Tạo List

In [4]:
height = []
weight = []

file_path_h = 'heights_1.txt'
file_path_w = 'weights_1.txt'

with open(file_path_h, 'r', encoding='utf-8-sig') as file : 
    for line in file : 
        height.append(line.strip())

with open(file_path_w, 'r', encoding='utf-8-sig') as file : 
    for line in file : 
        weight.append(line.strip())

height_str = ''.join(height)
weight_str = ''.join(weight)

height = [float(x) for x in height_str.split(',')]
weight = [float(x) for x in weight_str.split(',')]

print(height)
print(weight)


[74.0, 74.0, 72.0, 72.0, 73.0, 69.0, 69.0, 71.0, 76.0, 71.0, 73.0, 73.0, 74.0, 74.0, 69.0, 70.0, 73.0, 75.0, 78.0, 79.0, 76.0, 74.0, 76.0, 72.0, 71.0, 75.0, 77.0, 74.0, 73.0, 74.0, 78.0, 73.0, 75.0, 73.0, 75.0, 75.0, 74.0, 69.0, 71.0, 74.0, 73.0, 73.0, 76.0, 74.0, 74.0, 70.0, 72.0, 77.0, 74.0, 70.0, 73.0, 75.0, 76.0, 76.0, 78.0, 74.0, 74.0, 76.0, 77.0, 81.0, 78.0, 75.0, 77.0, 75.0, 76.0, 74.0, 72.0, 72.0, 75.0, 73.0, 73.0, 73.0, 70.0, 70.0, 70.0, 76.0, 68.0, 71.0, 72.0, 75.0, 75.0, 75.0, 75.0, 68.0, 74.0, 78.0, 71.0, 73.0, 76.0, 74.0, 74.0, 79.0, 75.0, 73.0, 76.0, 74.0, 74.0, 73.0, 72.0, 74.0, 73.0, 74.0, 72.0, 73.0, 69.0, 72.0, 73.0, 75.0, 75.0, 73.0, 72.0, 72.0, 76.0, 74.0, 72.0, 77.0, 74.0, 77.0, 75.0, 76.0, 80.0, 74.0, 74.0, 75.0, 78.0, 73.0, 73.0, 74.0, 75.0, 76.0, 71.0, 73.0, 74.0, 76.0, 76.0, 74.0, 73.0, 74.0, 70.0, 72.0, 73.0, 73.0, 73.0, 73.0, 71.0, 74.0, 74.0, 72.0, 74.0, 71.0, 74.0, 73.0, 75.0, 75.0, 79.0, 73.0, 75.0, 76.0, 74.0, 76.0, 78.0, 74.0, 76.0, 72.0, 74.0, 76.0, 74.

In [ ]:
# Ý 1: Tạo mảng array cho height : 
arr_height = np.array(height)
arr_height

array([74., 74., 72., ..., 75., 75., 73.])

In [ ]:
# Ý 2: Taọ mảng array cho weight : 
arr_weight = np.array(weight)
arr_weight

array([180., 215., 210., ..., 205., 190., 195.])

In [ ]:
# Ý 3: inch sang m là 0.0254 : 
arr_height_m = arr_height * 0.0254
arr_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [ ]:
# Ý 4: pound sang kg là 0.453592 : 
arr_weight_kg = arr_weight * 0.453592
arr_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [ ]:
# Ý 5: Tính BMI : 
arr_bmi = arr_weight_kg / (arr_height_m * arr_height_m)
arr_bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

In [ ]:
# ý 6: Giá trị ở vị trí index = 50 : 
arr_weight_kg[50]

np.float64(90.7184)

In [ ]:
# Ý 7: Phần tử có vị trí index từ 100 đến 110 : 
arr_height_m_100 = arr_height_m[100:111]
arr_height_m_100

array([1.8542, 1.8796, 1.8288, 1.8542, 1.7526, 1.8288, 1.8542, 1.905 ,
       1.905 , 1.8542, 1.8288])

In [ ]:
# Ý 8: Cầu thủ bóng chày có bmi < 21 : 
arr_bmi_if = np.where(arr_bmi < 21)[0] # hàm np.where() tìm vị trí index dựa trên điều kiện có trong ngoặc 
arr_bmi_21 = arr_bmi[arr_bmi_if]
arr_bmi_21

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

In [17]:
# ý 9: Chiều cao trung bình và cân nặng trung bình của các cầu thủ : (Dùng hàm np.mean()để kiểm tra số trung bình có trong array)
arr_height_medium = np.mean(arr_height_m)
arr_weight_medium = np.mean(arr_weight_kg)
print(arr_height_medium, arr_weight_medium)

1.8717172413793102 91.33019058916256


In [18]:
# ý 10 : Chiều cao và cân nặng lớn nhất của các cầu thủ : 
arr_height_max = np.max(arr_height_m)
arr_weight_max = np.max(arr_weight_kg)
print(arr_height_max, arr_weight_max)

2.1082 131.54167999999999


In [19]:
# ý 11 : CHiều cao và cân nặng nhỏ nhất của các cầu thủ : 
arr_height_min = np.min(arr_height_m)
arr_weight_min = np.min(arr_weight_kg)
print(arr_height_min, arr_weight_min)

1.7018 68.0388
