In [2]:
import numpy as np 

### Ý 1

In [3]:
arr = np.zeros(10)
arr[5] = 1
arr_zeros = arr
arr_zeros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### Ý 2

In [ ]:
arr_h = np.arange(10,25)
arr_f = arr_h[::-1]
arr_f #  đảo ngược của arr_h

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

### Ý 3 

In [10]:
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_1 = arr_k[arr_k != 0]
arr_1

array([1, 2, 8, 2, 1, 3, 5])

### Ý 4

In [13]:
arr_add = np.append(arr_1, [10,20])
arr_add

array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

### Ý 5

In [14]:
arr_add_2 = np.insert(arr_add, 5, 100)
arr_add_2

array([  1,   2,   8,   2,   1, 100,   3,   5,  10,  20])

### Ý 6

In [15]:
arr_add_3 = np.delete(arr_add_2, [0,1,2])
arr_add_3

array([  2,   1, 100,   3,   5,  10,  20])