### Ý 1 

In [47]:
import numpy as np 

arr = np.full((3,3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Ý 2 : 

In [48]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = arr_1D.reshape((3,3))
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
col_1 = arr_2D[:,0].copy()
col_3 = arr_2D[:,2].copy()

arr_2D[:,0] = col_3
arr_2D[:,2] = col_1       # lưu ý dùng arr_2D[:,0] chứ không dùng arr_2D[:, 0]

arr_2D

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Ý 3 : 

In [50]:
row_1 = arr_2D[0].copy()
row_2 = arr_2D[1].copy()

arr_2D[0] = row_2
arr_2D[1] = row_1

arr_2D

array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])

Ý 4 : 

In [51]:
arr_2D = arr_2D[::-1]
arr_2D  # Đảo dòng 

array([[8, 7, 6],
       [2, 1, 0],
       [5, 4, 3]])

Ý 5 : 

In [52]:
arr_2D = arr_2D[:, ::-1]
arr_2D

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

Ý 6 : 

In [55]:
# kiểm tra xem array có giá trị rỗng không 
arr_2D_null = np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9],[4,5,6]]) # NaN : not a number : giá trị rỗng 
print("Array trên có bị rỗng không ? ", np.isnan(arr_2D_null).any()) # không thẻe dùng size, phải dùng isnan

Array trên có bị rỗng không ?  True


Ý 7 : 

In [57]:
# thay thế giá trị null bằng 0 
arr_2D_null[np.isnan(arr_2D_null)] = 0 
arr_2D_null

array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])