In [1]:
import numpy as np 

arr_a = [1,2,3,2,3,4,3,4,5,6]
arr_b = [7,2,10,2,7,4,9,4,9,8]


### ý 1 

In [4]:
arr_c = np.array(list(set(arr_a) & set(arr_b)))
arr_c

array([2, 4])

### ý 2

In [6]:
arr_d = np.array(list(set(arr_a) - set(arr_b)))
arr_d

array([1, 3, 5, 6])

### ý 3 

In [11]:
arr_e = np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
np.sort(arr_f)

array([ 6,  6,  8,  9, 10])