In [1]:
import numpy as np 

In [2]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [3]:
np.array([3.4,1,2,3])

array([3.4, 1. , 2. , 3. ])

In [4]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a1 = np.array([1,2,3,4])

In [6]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3], 
              [4,5,6]])

In [11]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape # dạng (hàng, cột)

(2, 3)

In [ ]:
a2.ndim # chiều 

2

In [15]:
a2.size # Tổng các giá trị trong numpy


6

### tạo hàm numpy

In [24]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [ ]:
np.linspace(0,1, 5) # chia đều khoảng 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### RANDOM

In [26]:
# seed : giữ những con số giá trị ngẫu nhiên 
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [27]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [28]:
np.random.randint(0,10, (4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]], dtype=int32)

### Array indexing & slicing

In [30]:
x1 = np.random.randint(20, size=6)
x1

array([ 3, 12, 10, 11,  4,  6], dtype=int32)

In [34]:
x1[4], x1[5], x1[-1]

(np.int32(4), np.int32(6), np.int32(6))

### slicing

In [35]:
x1

array([ 3, 12, 10, 11,  4,  6], dtype=int32)

In [36]:
x1[0:3]

array([ 3, 12, 10], dtype=int32)

In [37]:
x1[2:4]

array([10, 11], dtype=int32)

In [38]:
x1[::2]

array([ 3, 10,  4], dtype=int32)

### Reshaping of Array & Transpose

In [40]:
grid = np.arange(1,10)
grid.shape

(9,)

In [41]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x = np.array([1,2,3])
x.shape

(3,)

In [44]:
x.reshape((1,3)).shape

(1, 3)

In [46]:
x = np.array([[1., 2.], [3., 4.]])
x 

array([[1., 2.],
       [3., 4.]])

In [ ]:
x.T # transpose chuyển hàng thành cột 

array([[1., 3.],
       [2., 4.]])

Array COncatenation and Spliting

In [49]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [50]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [51]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((grid,grid)) # axis = 0 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
# vstack
x = np.array([1,2,3])
grid = np.array([[4,5,6],
                 [7,8,9]])
np.vstack((x, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# horizontally stack the arrays : hstack
y = np.array([[99],
              [99]])
np.hstack((y, grid))

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

### Splitting of arrays

In [57]:
x = np.array([1,2,3,99,69,3,2,1])


In [58]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

### Broadcasting and Vecdtorize operations

In [59]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a + 5 # broadcasting 

array([5, 6, 7])

In [62]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
a.shape, b.shape

((3,), (3, 3))

In [64]:
a + b 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [66]:
c = np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [67]:
a + c 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays

In [73]:
list_number = [1,2,3]

In [74]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [ ]:
sum(ll) # python sum 

np.int64(6)

In [ ]:
np.sum(ll) # numpy sum 

np.int64(6)

In [79]:
# creat a massive numpy array 
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [80]:
%timeit sum(massive_array) # python built-iin function sum()
%timeit np.sum(massive_array) # Numpy's np.sum

518 μs ± 36.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.76 μs ± 65.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [81]:
np.mean(massive_array)

np.float64(0.5009195232413979)

In [82]:
np.max(massive_array)

np.float64(0.9998556266062902)

In [83]:
np.min(massive_array)

np.float64(0.00034494409119278924)

In [84]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)

np.std(dog_height)

np.float64(147.32277488562318)

In [85]:
np.var(dog_height)

np.float64(21704.0)

In [86]:
np.sqrt(np.var(dog_height))

np.float64(147.32277488562318)

### Sorting Arrays

In [87]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [88]:
np.argsort(x)

array([1, 0, 3, 2, 4])

In [89]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))

In [90]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [ ]:
np.sort(MatA, axis = 0) # axis = 0 là cột 

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [ ]:
np.sort(MatA, axis=1) # axis = 1 là hàng

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

### Linear Algebra

In [93]:
A = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9]])


In [94]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [ ]:
# A (3x3) dot product B ( 3x2)


In [ ]:
A.dot(B) # tích vô hướng trong đại số tuyến tính

array([[20, 14],
       [56, 41],
       [92, 68]])

In [97]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Dot Product Example

In [98]:
# Number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size = (5,3))


In [99]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [100]:
# creat weekly_sales DataFrame 
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [101]:
#creat a price array 
prices = np.array([10, 8, 12])

In [102]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["A", "P", "C"] )

In [103]:
butter_prices

A  P   C
Price  10  8  12

In [106]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices

ValueError: matrices are not aligned